### ISSUE TITLE
Node-red crash after database update

### ISSUE THREAD

**Issue by joakaidi** [phantom21/node-red-node-firebird#5]
After a firebird update my node-red crashes.
Here the log:

0|node-red | TypeError [ERR_UNKNOWN_ENCODING]: Unknown encoding: null
0|node-red |     at stringSlice (buffer.js:626:9)
0|node-red |     at Buffer.toString (buffer.js:659:10)
0|node-red |     at readRec (/root/.node-red/node_modules/node-firebird/lib/messages.js:95:39)
0|node-red |     at search (/root/.node-red/node_modules/node-firebird/lib/messages.js:108:27)
0|node-red |     at /root/.node-red/node_modules/node-firebird/lib/messages.js:54:21
0|node-red |     at FSReqCallback.wrapper [as oncomplete] (fs.js:478:5)

How can I resolve this error?

**Comment by geopardyonok** [comment]
I have the same problem. Pleas help.
